<?php
/**
 * @file
 * satellite_socialmedia_integration.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function satellite_socialmedia_integration_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_displays';
  $strongarm->value = array(
    'facebook_share' => 1,
    'twitter_widget' => 1,
    'facebook_like' => 1,
    'google_plus_one' => 1,
    'linkedin_share_button' => 0,
    'pinterest_button' => 0,
  );
  $export['service_links_displays'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_action';
  $strongarm->value = 'like';
  $export['service_links_fl_action'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_colorscheme';
  $strongarm->value = 'light';
  $export['service_links_fl_colorscheme'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_font';
  $strongarm->value = '';
  $export['service_links_fl_font'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_height';
  $strongarm->value = '21';
  $export['service_links_fl_height'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_layout';
  $strongarm->value = 'button_count';
  $export['service_links_fl_layout'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_show_faces';
  $strongarm->value = 'false';
  $export['service_links_fl_show_faces'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fl_width';
  $strongarm->value = '100';
  $export['service_links_fl_width'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_fs_type';
  $strongarm->value = 'button_count';
  $export['service_links_fs_type'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_gpo_annotation';
  $strongarm->value = '';
  $export['service_links_gpo_annotation'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_gpo_size';
  $strongarm->value = '';
  $export['service_links_gpo_size'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_gpo_width';
  $strongarm->value = '300';
  $export['service_links_gpo_width'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_lsb_countmode';
  $strongarm->value = 'right';
  $export['service_links_lsb_countmode'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_pb_countlayout';
  $strongarm->value = 'horizontal';
  $export['service_links_pb_countlayout'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'service_links_tw_data_count';
  $strongarm->value = 'horizontal';
  $export['service_links_tw_data_count'] = $strongarm;

  return $export;
}
