<?php

/**
 * @file
 * Constants needed in satellite.profile as well as satellite.install when satellite.profile is not loaded.
 */

/** Minimum required PHP version */
define('SATELLITE_MINIMUM_PHP', '5.3.2');
/** Current Satellite major & minor version */
define('SATELLITE_BASE_VERSION', '4.6');
/** Database table name for Satellite messages */
define('SATELLITE_NOTIFICATIONS_TABLE', 'satellite_messages');
